export const projects = [
  { dateL:     "2000",
    img:       "media/group.jpg",
    gif:       "",
    text:      "About me",
    right:     "XX",
    detail:    "Brazilian living in Lisbon, Portugal.<br>Passionate about engineering, filmmaking, photography, optics and architecture.<br>Fluent in English.<br>Student at ETIC Lisboa.<br><br>Contact: valdir.nvs@hotmail.com<br>Insta: @val.nevs",
    youtube:   ""},
  { dateL:     "JUL 2025",
    img:       "media/placeholder.jpg",
    gif:       "",
    text:      "Short film - Camera",
    right:     "XX",
    detail:    "Behind‑the‑scenes of the short film.",
    youtube:   ""},
  { dateL:     "JUN 2025",
    img:       "media/bang.jpg",
    gif:       "media/bang.gif",
    text:      "Music Video - Camera",
    right:     "3 MIN",
    detail:    "KPOP Dance cover",
    youtube:   ""},
  { dateL:     "MAY 2025",
    img:       "media/clapper.jpg",
    gif:       "media/clapper.gif",
    text:      "Short film - Sound",
    right:     "30 MIN",
    detail:    "Recorded production sound and streamlined file workflow with batch-edit scripts and spreadsheet tracking for a 20-minute action thriller, shot in 13 days at 6 varied locations across Lisbon.",
    youtube:   ""},
  { dateL:     "JAN 2025",
    img:       "media/chapito.jpg",
    gif:       "media/chapito.gif",
    text:      "Documentary - Camera & Sound",
    right:     "13 MIN",
    detail:    "Documentary about Pascoal Furtado, a teacher at Chapitô, a circus school in Lisbon.",
    youtube:   "ztUn9QWYk_Y"},
  { dateL:     "OCT 2024",
    img:       "media/doclis.png",
    gif:       "",
    text:      "Film festival coverage",
    right:     "X DAYS",
    detail:    "Filmed B-roll and presentations for Doclisboa, Portugal’s leading international documentary film festival.",
    youtube:   "NPPzUJvmkq8"},
  { dateL:     "AUG 2024",
    img:       "media/seb.jpg",
    gif:       "media/seb.gif",
    text:      "Interview - Camera",
    right:     "4 MIN",
    detail:    "Interview about Sebastião Ogando - Inês Serra",
    youtube:   "__UxmK7BD68"},
  { dateL:      "AUG 2024",
    img:       "media/free.jpg",
    gif:       "media/free.gif",
    text:      "Short film - Camera",
    right:     "4 MIN",
    detail:    "Experimental short film.",
    youtube:   "FcrQnCTnG0M"},
  { dateL:     "JUN 2024",
    img:       "media/group1.png",
    gif:       "",
    text:      "TV Pilot - Crane Cam",
    right:     "31 MIN",
    detail:    "Behind‑the‑scenes of the crane cam setup for a TV pilot.",
    youtube:   "5LlSdajis7g"},
  { dateL:     "JUN 2024",
    img:       "media/redroom.jpg",
    gif:       "",
    text:      "TV Pilot - Crane Cam AC",
    right:     "30 MIN",
    detail:    "Assistant camera of the crane cam.",
    youtube:   ""},
  { dateL:     "MAY 2024",
    img:       "media/alges.png",
    gif:       "",
    text:      "Music Video - Camera",
    right:     "4 MIN",
    detail:    "Dance cover, RIIZE 라이즈 - 'Impossible'.",
    youtube:   "UsGJUCy7Mx0"},
  { dateL:     "APR 2024",
    img:       "media/cinema.png",
    gif:       "",
    text:      "Short film - Sound",
    right:     "4 MIN",
    detail:    "Sound recording https://vimeo.com/930022904",
    youtube:   ""},
  { dateL:     "FEB 2024",
    img:       "media/curta.jpg",
    gif:       "",
    text:      "Short",
    right:     "2 MIN",
    detail:    "A very short experimental piece.",
    youtube:   ""},
  { dateL:     "JAN 2024",
    img:       "media/people.png",
    gif:       "",
    text:      "Photography",
    right:     "2 MIN",
    detail:    "Behind the scenes photographs",
    youtube:   "ayyPyMsfCJo"},
  { dateL:     "JUN 2023",
    img:       "media/steady.png",
    gif:       "",
    text:      "Short",
    right:     "2 MIN",
    detail:    "Experimenting with steady cam techniques.",
    youtube:   ""},
  { dateL:     "DEC 2021",
    img:       "media/film.png",
    gif:       "",
    text:      "C‑41 Developing",
    right:     "XX",
    detail:    "C‑41 Developing",
    youtube:   ""},
  { dateL:     "JUN 2021",
    img:       "media/boat.png",
    gif:       "",
    text:      "Short",
    right:     "1 MIN",
    detail:    "A quick boating-themed video.",
    youtube:   ""},
  { dateL:     "OCT 2015",
    img:       "media/skydive.png",
    gif:       "",
    text:      "Camera animation",
    right:     "1 MIN",
    detail:    "Animating camera movements in 3D.",
    youtube:   ""},
  { dateL:     "CC0 1929",
    img:       "media/moon.jpg",
    gif:       "media/end.gif",
    text:      "",
    right:     "65MM",
    detail:    "Public domain footage from 1929.",
    youtube:   ""},
];